// external declaration of sound table:

extern far cdata SNDTBL_SOUND_TABLE;

// external declarations of addresses of sounds for direct access:

extern far cdata SX_apples;
extern far cdata SX_automatic_mode;
extern far cdata SX_bacon;
extern far cdata SX_beans;
extern far cdata SX_bread;
extern far cdata SX_candy;
extern far cdata SX_champagne;
extern far cdata SX_close;
extern far cdata SX_closet1_shelf1;
extern far cdata SX_closet1_shelf2;
extern far cdata SX_closet2_shelf1;
extern far cdata SX_closet2_shelf2;
extern far cdata SX_coke;
extern far cdata SX_cookies;
extern far cdata SX_croissant;
extern far cdata SX_eggs;
extern far cdata SX_foie_gras;
extern far cdata SX_gin;
extern far cdata SX_good_bye;
extern far cdata SX_happy_mood;
extern far cdata SX_ketchup;
extern far cdata SX_manual_mode;
extern far cdata SX_milk;
extern far cdata SX_ok_mood;
extern far cdata SX_open;
extern far cdata SX_open_mode;
extern far cdata SX_pasta;
extern far cdata SX_pate;
extern far cdata SX_pepper;
extern far cdata SX_repeat_command;
extern far cdata SX_sad_mood;
extern far cdata SX_salt;
extern far cdata SX_soda;
extern far cdata SX_spaghetti;
extern far cdata SX_sugar;
extern far cdata SX_tomatos;
extern far cdata SX_water;
extern far cdata SX_welcome;
extern far cdata SX_wine;

// constants defining sounds as entries in the sound table:

#define SND_apples              1
#define SND_automatic_mode      2
#define SND_bacon               3
#define SND_beans               4
#define SND_bread               5
#define SND_candy               6
#define SND_champagne           7
#define SND_close               8
#define SND_closet1_shelf1      9
#define SND_closet1_shelf2      10
#define SND_closet2_shelf1      11
#define SND_closet2_shelf2      12
#define SND_coke                13
#define SND_cookies             14
#define SND_croissant           15
#define SND_eggs                16
#define SND_foie_gras           17
#define SND_gin                 18
#define SND_good_bye            19
#define SND_happy_mood          20
#define SND_ketchup             21
#define SND_manual_mode         22
#define SND_milk                23
#define SND_ok_mood             24
#define SND_open                25
#define SND_open_mode           26
#define SND_pasta               27
#define SND_pate                28
#define SND_pepper              29
#define SND_repeat_command      30
#define SND_sad_mood            31
#define SND_salt                32
#define SND_soda                33
#define SND_spaghetti           34
#define SND_sugar               35
#define SND_tomatos             36
#define SND_water               37
#define SND_welcome             38
#define SND_wine                39

